import { NgModule } from '@angular/core';
import {
  DtAlertModule,
  DtAutocompleteModule,
  DtBreadcrumbsModule,
  DtButtonGroupModule,
  DtButtonModule,
  DtCardModule,
  DtChartModule,
  DtCheckboxModule,
  DtContextDialogModule,
  DtCopyToClipboardModule,
  DtCtaCardModule,
  DtExpandablePanelModule,
  DtExpandableSectionModule,
  DtFilterFieldModule,
  DtFormattersModule,
  DtFormFieldModule,
  DtIconModule,
  DtInlineEditorModule,
  DtInputModule,
  DtKeyValueListModule,
  DtLoadingDistractorModule,
  DtMicroChartModule,
  DtOverlayModule,
  DtPaginationModule,
  DtProgressBarModule,
  DtProgressCircleModule,
  DtRadioModule,
  DtSelectionAreaModule,
  DtSelectModule,
  DtShowMoreModule,
  DtSwitchModule,
  DtTableModule,
  DtTabsModule,
  DtTagModule,
  DtThemingModule,
  DtTileModule,
  DtToastModule,
} from '@dynatrace/angular-components';

const DT_MODULES = [
  DtAlertModule,
  DtAutocompleteModule,
  DtBreadcrumbsModule,
  DtButtonModule,
  DtButtonGroupModule,
  DtCardModule,
  DtChartModule,
  DtCheckboxModule,
  DtContextDialogModule,
  DtCopyToClipboardModule,
  DtCtaCardModule,
  DtExpandablePanelModule,
  DtExpandableSectionModule,
  DtFilterFieldModule,
  DtFormFieldModule,
  DtFormattersModule,
  DtIconModule,
  DtInlineEditorModule,
  DtInputModule,
  DtKeyValueListModule,
  DtLoadingDistractorModule,
  DtMicroChartModule,
  DtOverlayModule,
  DtPaginationModule,
  DtProgressBarModule,
  DtProgressCircleModule,
  DtRadioModule,
  DtSelectModule,
  DtSelectionAreaModule,
  DtShowMoreModule,
  DtSwitchModule,
  DtTableModule,
  DtTabsModule,
  DtTagModule,
  DtThemingModule,
  DtTileModule,
  DtToastModule,
];

/**
 * NgModule that includes all Dynatrace angular components modules that are required to serve the examples.
 */
@NgModule({
  imports: [
    ...DT_MODULES,
  ],
  exports: [
    ...DT_MODULES,
  ],
})
export class ExamplesAppDynatraceModule { }
