import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'dev-app',
  styleUrls: ['devapp.component.scss'],
  templateUrl: 'devapp.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DevApp {
  navItems = [
    { name: 'Alert', route: '/alert' },
    { name: 'Autocomplete', route: '/autocomplete' },
    { name: 'Bar indicator', route: '/bar-indicator' },
    { name: 'Breadcrumbs', route: '/breadcrumbs' },
    { name: 'Button', route: '/button' },
    { name: 'Button-group', route: '/button-group' },
    { name: 'Card', route: '/card' },
    { name: 'Chart', route: '/chart' },
    { name: 'Checkbox', route: '/checkbox' },
    { name: 'Consumption', route: '/consumption' },
    { name: 'Context-dialog', route: '/context-dialog' },
    { name: 'Copy-to-clipboard', route: '/copy-to-clipboard' },
    { name: 'Cta-card', route: '/cta-card' },
    { name: 'Drawer', route: '/drawer' },
    { name: 'Expandable-panel', route: '/expandable-panel' },
    { name: 'Expandable-section', route: '/expandable-section' },
    { name: 'Filter-field', route: '/filter-field' },
    { name: 'Form-field', route: '/form-field' },
    { name: 'Formatters', route: '/formatters' },
    { name: 'Highlight', route: '/highlight' },
    { name: 'Icon', route: '/icon' },
    { name: 'Info-group', route: '/info-group' },
    { name: 'Inline-editor', route: '/inline-editor' },
    { name: 'Input', route: '/input' },
    { name: 'Key-value-list', route: '/key-value-list' },
    { name: 'Link', route: '/link' },
    { name: 'Loading-distractor', route: '/loading-distractor' },
    { name: 'Micro-chart', route: '/micro-chart' },
    { name: 'Overlay', route: '/overlay' },
    { name: 'Pagination', route: '/pagination' },
    { name: 'Progress-bar', route: '/progress-bar' },
    { name: 'Progress-circle', route: '/progress-circle' },
    { name: 'Radio', route: '/radio' },
    { name: 'Select', route: '/select' },
    { name: 'Selection-area', route: '/selection-area' },
    { name: 'Show-more', route: '/show-more' },
    { name: 'Switch', route: '/switch' },
    { name: 'Table', route: '/table' },
    { name: 'Tabs', route: '/tabs' },
    { name: 'Tag', route: '/tag' },
    { name: 'Tile', route: '/tile' },
    { name: 'Timeline-chart', route: '/timeline-chart' },
    { name: 'Toggle-button-group', route: '/toggle-button-group' },
    { name: 'Toast', route: '/toast' },
    { name: 'TreeTable', route: '/tree-table' },
  ];
  selectedTheme = 'turquoise';
  themes = [
    { value: 'turquoise', name: 'Turquoise' },
    { value: 'turquoise:dark', name: 'Turquoise dark' },
    { value: 'blue', name: 'Blue' },
    { value: 'blue:dark', name: 'Blue dark' },
    { value: 'purple', name: 'Purple' },
    { value: 'purple:dark', name: 'Purple dark' },
    { value: 'royalblue', name: 'Royalblue' },
    { value: 'royalblue:dark', name: 'Royalblue dark' },
  ];
}
